ID-B-20
KaPodgaets/PetFam pull request #27
Opened 2024-11-21 08:46 UTC by KaPodgaets

2024-11-21 11:11 UTC, KirillSachkov requested changes

2024-11-21 11:11 UTC, KirillSachkov commented on PetFam.Backend/src/Accounts/PetFam.Accounts.Application/RegisterUser/RegisterUserHandler.cs
> +        transaction.Commit();
transaction.Commit должно быть в блоке try, потому что именно при коммите у тебя может быть exception

2024-11-21 11:11 UTC, KirillSachkov commented on PetFam.Backend/src/Accounts/PetFam.Accounts.Application/RegisterUser/RegisterUserHandler.cs
> +            throw new ApplicationException("An error occured while registering user", e);
не нужно дальше прокидывать exception, лучше вернуть Result с ошибкой

2024-11-21 11:11 UTC, KirillSachkov commented on PetFam.Backend/src/Accounts/PetFam.Accounts.Application/RegisterUser/RegisterUserHandler.cs
> +        transaction.Commit();
в остальных местах, где используется транзакция, исправить это поведение

2024-11-21 11:11 UTC, KirillSachkov commented on PetFam.Backend/src/Accounts/PetFam.Accounts.Application/RegisterUser/RegisterUserHandler.cs
> +        transaction.Commit();
по-моему есть асинхронная версия этого метода, и rollback тоже

2024-11-24 15:51 UTC, KaPodgaets commented on PetFam.Backend/src/Accounts/PetFam.Accounts.Application/RegisterUser/RegisterUserHandler.cs
> +        transaction.Commit();
nope. https://learn.microsoft.com/en-us/dotnet/api/System.Data.IDbTransaction?view=net-8.0

2024-11-24 18:13 UTC, KirillSachkov approved these changes

2024-11-25 06:59 UTC, merged