ID-B-4
KaPodgaets/PetFam pull request #5
Opened 2024-08-29 20:47 UTC by KaPodgaets

2024-08-29 21:06 UTC, YADARAN1 requested changes

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/AccountInfo.cs
> +        public int BankId { get; set; }
Удалить

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Pet.cs
> +        public int Weight { get; set; }
Вес и рост в double

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Pet.cs
> +        public Guid Id { get; set; }
Всем свойствам добавить private set

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Pet.cs
> +        public void UpdateStatus(PetStatus newStatus)
Удалить

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Pet.cs
> +        public void UpdateAddress(string newAddress)
Удалить

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Pet.cs
> +        public void UpdateWeight(int newWeight)
Удалить

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Pet.cs
> +        public void UpdateHeight(int newHeight)
Удалить

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Volunteer.cs
> +        public Guid Id { get; set; }
Всем свойствам добавить private set

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Volunteer.cs
> +        public string FullName { get; set; } = string.Empty;
Из FullName сделать VO

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Volunteer.cs
> +        public List<SocialMediaLink> Links { get; set; } = [];
Должно быть так private readonly List _links = []; IReadOnlyList => _links Сделать так со всеми листами

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Volunteer.cs
> +        public void AddPet(Pet pet)
Удалить

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Volunteer.cs
> +        public void RemovePet(Guid petId)
Удалить

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Volunteer.cs
> +        public void UpdatePetStatus(Guid petId, PetStatus newStatus)
Удалить

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Volunteer.cs
> +            (Pets.Where(x => x.Status == PetStatus.Adopted).Count());
Просто получить количество, без where

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Volunteer.cs
> +        public int PetsLookingForHomeCount =>
.

2024-08-29 21:06 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Volunteer.cs
> +        public int PetsOnTreatment =>
.

2024-08-29 21:19 UTC, KaPodgaets commented on PetFam.Backend/src/PetFam.Domain/Models/Volunteer.cs
> +            (Pets.Where(x => x.Status == PetStatus.Adopted).Count());
в задаче указано получить кол-во животных которые нашли дом, ищут дом или на лечении. заменить это на 1 свойство "кол-во животных"?

2024-08-30 08:33 UTC, YADARAN1 requested changes

2024-08-30 08:33 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/AccountInfo.cs
> +            if (string.IsNullOrWhiteSpace(number) ||
Проверку  сделать для каждого свойства отдельно

2024-08-30 08:33 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/FullName.cs
> +            if (string.IsNullOrWhiteSpace(firstName) ||
Проверку сделать для каждого свойства отдельно

2024-08-30 08:33 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/FullName.cs
> +        public string LastName { get; private set; }
Добавить свойство "Отчество" и сделать его nullable

2024-08-30 08:33 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/PetPhoto.cs
> +        public string FilePath { get; set; } = string.Empty;
Cделать конструктор и валидацию для каждого свойства отдельно

2024-08-30 08:33 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Requisite.cs
> +        public string Name { get; set; } = string.Empty;
Cделать конструктор и валидацию для каждого свойства отдельно

2024-08-30 08:33 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/SocialMediaLink.cs
> +        public string Name { get; set; } = string.Empty;
Cделать конструктор и валидацию для каждого свойства отдельно

2024-08-30 08:33 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/Volunteer.cs
> +            (Pets.Count(x => x.Status == PetStatus.Adopted));
Нам нужно обращаться не к Pets, а к приватному листу _pets

2024-08-30 11:46 UTC, KaPodgaets commented on PetFam.Backend/src/PetFam.Domain/Models/Volunteer.cs
> +            (Pets.Count(x => x.Status == PetStatus.Adopted));
В чем разница если это одно и тоже?

2024-08-30 12:30 UTC, KaPodgaets commented on PetFam.Backend/src/PetFam.Domain/Models/AccountInfo.cs
> +            if (string.IsNullOrWhiteSpace(number) ||
зачем?

2024-08-30 13:27 UTC, YADARAN1 approved these changes

2024-08-30 13:27 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/AccountInfo.cs
> +                throw new ArgumentException("Account number cannot be empty.");
Когда дойдёшь до реализации паттерна Result, переделать

2024-08-30 13:28 UTC, YADARAN1 commented on PetFam.Backend/src/PetFam.Domain/Models/AccountInfo.cs
> +                throw new ArgumentException("Account number cannot be empty.");
Выбрасывать ошибки ArgumentException не очень хорошо, потому-что они останавливают работу приложений, для этого мы будем использовать паттерн Result

2024-08-30 13:41 UTC, merged